name: qlib_predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=23.3,<24.1
  - setuptools>=68
  - wheel
  - cython
  - numpy>=1.24,<2.0
  - pandas>=2.0,<2.3
  - scipy
  - scikit-learn
  - statsmodels
  - joblib>=1.1,<1.4
  - pyarrow
  - pyyaml
  - ruamel.yaml>=0.17.38
  - requests
  - tqdm
  - loguru
  - fire
  - filelock>=3.16.0
  - redis-py
  - pymongo
  - dill
  - mlflow
  - sqlalchemy<2
  - flask<3
  - werkzeug<3
  - lightgbm
  - xgboost
  - cvxpy
  - matplotlib
  - seaborn
  - plotly
  - mplfinance
  - ta-lib
  - jupyter
  - nbconvert
  - ipykernel
  - pip:
      - -r a6_customizations/requirements.txt
